spring:
  application:
    name:
      MailService
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
#    consumer:
#      group-id: my-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: killermon3000@gmail.com
    password: dhkvtvygfwyvcfdr

    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true
server:
  port: 8081
