CREATE TABLE logs
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action      VARCHAR(255),
    table_name  VARCHAR(255),
    change_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    details     VARCHAR(255),
    CONSTRAINT logs_pkey PRIMARY KEY (id)
);

CREATE TABLE booking
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       TIMESTAMP WITHOUT TIME ZONE,
    doctor_id  INTEGER                                  NOT NULL,
    service_id INTEGER                                  NOT NULL,
    user_id    INTEGER                                  NOT NULL,
    CONSTRAINT booking_pkey PRIMARY KEY (id)
);

CREATE TABLE doctors
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    branch_id INTEGER                                  NOT NULL,
    CONSTRAINT doctors_pkey PRIMARY KEY (id)
);

CREATE TABLE service
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    price INTEGER,
    CONSTRAINT service_pkey PRIMARY KEY (id)
);

CREATE TABLE services_doctors
(
    doctor_id  INTEGER                                  NOT NULL,
    service_id INTEGER                                  NOT NULL,
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL
);

CREATE TABLE user_data
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255),
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    password     VARCHAR(255),
    phone_number VARCHAR(255),
    role         VARCHAR(255),
    CONSTRAINT user_data_pkey PRIMARY KEY (id)
);

CREATE TABLE branches
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                             NOT NULL,
    address VARCHAR(255)                             NOT NULL,
    CONSTRAINT branches_pkey PRIMARY KEY (id)
);

CREATE VIEW today_bookings AS
SELECT id,
       date,
       doctor_id,
       service_id,
       user_id
FROM booking b
WHERE (date_trunc('day'::text, date) = date_trunc('day'::text, now()));

ALTER TABLE service
    ADD CONSTRAINT ukadgojnrwwx9c3y3qa2q08uuqp UNIQUE (name);

ALTER TABLE user_data
    ADD CONSTRAINT ukdhxuydjj5l1vds6s9eex23dcr UNIQUE (email);

ALTER TABLE user_data
    ADD CONSTRAINT ukg35kfcph8ainb2wk4swa20wta UNIQUE (phone_number);

ALTER TABLE branches
    ADD CONSTRAINT branches_address_key UNIQUE (address);

ALTER TABLE branches
    ADD CONSTRAINT branches_name_key UNIQUE (name);

ALTER TABLE doctors
    ADD CONSTRAINT doctors_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE services_doctors
    ADD CONSTRAINT fk87wogmn017g3m7vqr3tnsp7br FOREIGN KEY (service_id) REFERENCES service (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE booking
    ADD CONSTRAINT fkcebnlefwi9r13txu8btclnmsu FOREIGN KEY (service_id) REFERENCES service (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE services_doctors
    ADD CONSTRAINT fkdva261j5py7tvx0y4h4uc8nho FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE booking
    ADD CONSTRAINT fkrh1j55l2k4a2eqo6a9igu89b8 FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE booking
    ADD CONSTRAINT user_booking_fkey FOREIGN KEY (user_id) REFERENCES user_data (id) ON UPDATE NO ACTION ON DELETE CASCADE;